### ISSUE TITLE
Can not load model

### ISSUE THREAD

**Issue by yimingli1998** [Ulvetanna/EikoNet#1]
Hi, 

Thanks for your great work! I was running the colab code. However, when I load the downloaded checkpoints, there is an error:

```
Downloading 1PFjT4tcoPAJAb9d5SSmUZh2cUmby-z_H into ./Experiments/Section5_VelocityModelExperiments/Homogenous/Homogeneous.pt... Done.
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[<ipython-input-7-ec51cb0f3d9a>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 # Loading Model and plotting output
----> 6 model.load('{}/Homogeneous.pt'.format(filePath))

2 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1244             "functionality.")
   1245 
-> 1246     magic_number = pickle_module.load(f, **pickle_load_args)
   1247     if magic_number != MAGIC_NUMBER:
   1248         raise RuntimeError("Invalid magic number; corrupt file?")

UnpicklingError: invalid load key, '<'.
```

How to solve this issue? Is there anything wrong?

Best

**Comment by Ulvetanna** [comment]
Thanks for the interest in the code. This is an issue with Colab now having restrictions of the size of data. 

All models are downloaded from this google drive - https://drive.google.com/drive/folders/1DlOT54zaM64mNzDbjxNVrQq_EbZiBhXg?usp=sharing

For the meantime you will have to manually upload the trained network to colab. I will take a look shortly to think of a long term fix

**Comment by Ulvetanna** [comment]
I have supplied the manual links for downloading and uploading in the Colab. Due to Googles new transfer rules the old method did not work and this is the only way forward
